version: '3.8'


services:
  web:
    build: ./app
    container_name: devops-lab-web
    ports:
      - "8888:80"
    restart: unless-stopped
    volumes:
      - ./app/index.html:/usr/share/nginx/html/index.html
