apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
spec:
  selector:
    app: devops-lab            # находит поды с этим лейблом
  ports:
  - port: 80
    targetPort: 80
  type: NodePort               # доступен снаружи кластера
