name: Deploy DevOps Lab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ~/devops-lab
          git pull
          docker compose down
          docker compose up -d --build
          echo "✅ Deployed at $(date)"
